# Generated by Django 5.2.4 on 2025-09-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("via_email", "Email orqali"),
                    ("via_phone", "Telefon orqali"),
                ],
                max_length=20,
                verbose_name="Autentifikatsiya turi",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Email manzil",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                verbose_name="Telefon raqam",
            ),
        ),
    ]
