# Generated by Django 5.2.7 on 2025-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Nom"),
        ),
        migrations.AddField(
            model_name="income",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Nom"),
        ),
        migrations.AddField(
            model_name="income",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Nom"),
        ),
    ]
