# Generated by Django 5.2.6 on 2025-09-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="payment_method",
            field=models.CharField(
                choices=[("naqt", "Naqt"), ("karta", "Karta"), ("dollar", "Dollar")],
                max_length=20,
            ),
        ),
    ]
