# Generated by Django 5.2.4 on 2025-09-29 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_alter_income_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Summasi"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Sana"),
        ),
        migrations.AlterField(
            model_name="income",
            name="payment_method",
            field=models.CharField(
                choices=[("naqt", "Naqt"), ("karta", "Karta"), ("dollar", "Dollar")],
                max_length=20,
                verbose_name="To‘lov usuli",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="income",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
    ]
